package reviewdiff

import "strings"

func IsGeneratedPath(path string) bool {
	clean := strings.TrimPrefix(strings.ReplaceAll(path, "\\", "/"), "./")
	lower := strings.ToLower(clean)
	for _, prefix := range []string{"vendor/", "dist/", "build/", "coverage/", "node_modules/"} {
		if strings.HasPrefix(lower, prefix) || strings.Contains(lower, "/"+prefix) {
			return true
		}
	}
	return strings.HasSuffix(lower, ".min.js") || strings.HasSuffix(lower, ".min.css")
}

func IsLargeLockfile(path string, diffBytes int) bool {
	if diffBytes < LargeLockfileDiffBytes {
		return false
	}
	name := strings.ToLower(pathBase(path))
	switch name {
	case "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "composer.lock", "gemfile.lock", "poetry.lock", "pdm.lock", "cargo.lock", "go.sum":
		return true
	default:
		return strings.HasSuffix(name, ".lock")
	}
}

func IsLikelyBinaryPath(path string) bool {
	lower := strings.ToLower(pathBase(path))
	for _, suffix := range []string{
		".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif", ".ico", ".bmp", ".tif", ".tiff",
		".pdf", ".zip", ".gz", ".tgz", ".bz2", ".xz", ".7z", ".rar", ".tar",
		".jar", ".war", ".wasm", ".class", ".so", ".dylib", ".dll", ".exe",
		".mp3", ".wav", ".flac", ".ogg", ".mp4", ".mov", ".avi", ".webm",
		".woff", ".woff2", ".ttf", ".otf", ".eot",
	} {
		if strings.HasSuffix(lower, suffix) {
			return true
		}
	}
	return false
}

func HasGeneratedHeader(patch string) bool {
	header := patch
	if len(header) > 4096 {
		header = header[:4096]
	}
	return strings.Contains(header, "Code generated") ||
		strings.Contains(header, "DO NOT EDIT") ||
		strings.Contains(header, "Generated by")
}

func MarkGeneratedAndLarge(file ChangedFile, opts RenderOptions) ChangedFile {
	opts = normalizeOptions(opts)
	diffBytes := len(file.Patch)
	if file.Generated || IsGeneratedPath(file.Path) || (file.OldPath != "" && IsGeneratedPath(file.OldPath)) || HasGeneratedHeader(file.Patch) {
		file.Generated = true
	}
	if file.Large || IsLargeLockfile(file.Path, diffBytes) || (file.OldPath != "" && IsLargeLockfile(file.OldPath, diffBytes)) || diffBytes > opts.MaxFileDiffBytes {
		file.Large = true
	}
	return file
}

func pathBase(path string) string {
	path = strings.ReplaceAll(path, "\\", "/")
	if idx := strings.LastIndex(path, "/"); idx >= 0 {
		return path[idx+1:]
	}
	return path
}
