package reviewdiff

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/herd-os/herd/internal/git"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLocalCollectorCollectsChangedFiles(t *testing.T) {
	dir, g := initLocalCollectorRepo(t)
	baseSHA := gitOutput(t, dir, "rev-parse", "HEAD")

	require.NoError(t, g.CreateBranch("feature", "main"))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "modified.txt"), []byte("old\nnew\n"), 0644))
	require.NoError(t, os.Remove(filepath.Join(dir, "deleted.txt")))
	require.NoError(t, os.Rename(filepath.Join(dir, "rename_old.txt"), filepath.Join(dir, "rename_new.txt")))
	require.NoError(t, os.Chmod(filepath.Join(dir, "mode.sh"), 0755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "added.txt"), []byte("added\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "binary.dat"), []byte{0x00, 0x01, 0x02, 0x03}, 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "gen_header.go"), []byte("// Code generated by test. DO NOT EDIT.\npackage gen\n"), 0644))
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "dist"), 0755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "dist", "app.js"), []byte("console.log('built');\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "large.txt"), []byte(strings.Repeat("large line\n", 6000)), 0644))
	runLocalGit(t, dir, "add", "-A")
	runLocalGit(t, dir, "commit", "-m", "feature changes")
	headSHA := gitOutput(t, dir, "rev-parse", "HEAD")

	diff, err := LocalCollector{Git: g}.Collect(context.Background(), CollectRequest{
		PRNumber: 42,
		BaseRef:  "main",
		HeadRef:  "feature",
		BaseSHA:  baseSHA,
		HeadSHA:  headSHA,
	})
	require.NoError(t, err)

	assert.Equal(t, 42, diff.PRNumber)
	assert.Equal(t, LocalGitSource, diff.Source)
	assert.Equal(t, baseSHA, diff.BaseSHA)
	assert.Equal(t, headSHA, diff.HeadSHA)
	assert.Empty(t, diff.Warnings)

	files := filesByPath(diff.Files)
	require.Contains(t, files, "added.txt")
	assert.Equal(t, ChangeAdded, files["added.txt"].Status)
	assert.Equal(t, 1, files["added.txt"].Additions)
	assert.Contains(t, files["added.txt"].Patch, "+added")

	require.Contains(t, files, "modified.txt")
	assert.Equal(t, ChangeModified, files["modified.txt"].Status)
	assert.Equal(t, 1, files["modified.txt"].Additions)
	assert.Equal(t, 0, files["modified.txt"].Deletions)

	require.Contains(t, files, "deleted.txt")
	assert.Equal(t, ChangeDeleted, files["deleted.txt"].Status)
	assert.Equal(t, 1, files["deleted.txt"].Deletions)
	assert.Contains(t, files["deleted.txt"].Patch, "-delete me")

	require.Contains(t, files, "rename_new.txt")
	assert.Equal(t, ChangeRenamed, files["rename_new.txt"].Status)
	assert.Equal(t, "rename_old.txt", files["rename_new.txt"].OldPath)
	assert.Contains(t, files["rename_new.txt"].Patch, "rename_new.txt")

	require.Contains(t, files, "mode.sh")
	assert.Equal(t, ChangeModified, files["mode.sh"].Status)
	assert.Equal(t, "100644", files["mode.sh"].PreviousMode)
	assert.Equal(t, "100755", files["mode.sh"].CurrentMode)

	require.Contains(t, files, "binary.dat")
	assert.True(t, files["binary.dat"].Binary)
	assert.True(t, files["binary.dat"].Omitted)
	assert.Equal(t, "binary file", files["binary.dat"].OmitReason)

	require.Contains(t, files, "gen_header.go")
	assert.True(t, files["gen_header.go"].Generated)

	require.Contains(t, files, "dist/app.js")
	assert.True(t, files["dist/app.js"].Generated)

	require.Contains(t, files, "large.txt")
	assert.True(t, files["large.txt"].Large)
}

func TestLocalCollectorWarnsForPathDiffFailure(t *testing.T) {
	withFakeGit(t, `#!/bin/sh
if [ "$1" = "rev-parse" ]; then
  case "$2" in
    base*) echo base; exit 0 ;;
    head*) echo head; exit 0 ;;
  esac
fi
if [ "$1" = "diff" ] && [ "$2" = "--name-status" ]; then
  printf 'M\tbroken.go\n'
  exit 0
fi
if [ "$1" = "diff" ] && [ "$2" = "--numstat" ]; then
  printf '1\t1\tbroken.go\n'
  exit 0
fi
if [ "$1" = "diff" ]; then
  echo path diff failed >&2
  exit 1
fi
exit 1
`)

	diff, err := LocalCollector{Git: git.New(t.TempDir())}.Collect(context.Background(), CollectRequest{
		BaseSHA: "base",
		HeadSHA: "head",
	})
	require.NoError(t, err)

	require.Len(t, diff.Files, 1)
	assert.Equal(t, "broken.go", diff.Files[0].Path)
	assert.True(t, diff.Files[0].Omitted)
	assert.Equal(t, "file diff unavailable", diff.Files[0].OmitReason)
	assert.Contains(t, strings.Join(diff.Warnings, "\n"), "failed to collect diff for broken.go")
}

func TestLocalCollectorReturnsErrorForNameStatusFailure(t *testing.T) {
	withFakeGit(t, `#!/bin/sh
if [ "$1" = "rev-parse" ]; then
  echo "$2"
  exit 0
fi
if [ "$1" = "diff" ] && [ "$2" = "--name-status" ]; then
  echo name status failed >&2
  exit 1
fi
exit 1
`)

	_, err := LocalCollector{Git: git.New(t.TempDir())}.Collect(context.Background(), CollectRequest{
		BaseSHA: "base",
		HeadSHA: "head",
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "compute changed-file metadata")
}

func initLocalCollectorRepo(t *testing.T) (string, *git.Git) {
	t.Helper()
	dir := t.TempDir()
	runLocalGit(t, dir, "init", "-b", "main")
	runLocalGit(t, dir, "config", "user.email", "test@test.com")
	runLocalGit(t, dir, "config", "user.name", "Test")
	runLocalGit(t, dir, "config", "diff.renames", "true")
	require.NoError(t, os.WriteFile(filepath.Join(dir, "modified.txt"), []byte("old\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "deleted.txt"), []byte("delete me\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "rename_old.txt"), []byte("rename me\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "mode.sh"), []byte("#!/bin/sh\nexit 0\n"), 0644))
	runLocalGit(t, dir, "add", ".")
	runLocalGit(t, dir, "commit", "-m", "base")
	return dir, git.New(dir)
}

func filesByPath(files []ChangedFile) map[string]ChangedFile {
	byPath := make(map[string]ChangedFile, len(files))
	for _, file := range files {
		byPath[file.Path] = file
	}
	return byPath
}

func runLocalGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "git %v failed: %s", args, string(out))
}

func gitOutput(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "git %v failed: %s", args, string(out))
	return strings.TrimSpace(string(out))
}

func withFakeGit(t *testing.T, script string) {
	t.Helper()
	dir := t.TempDir()
	name := "git"
	if runtime.GOOS == "windows" {
		name = "git.bat"
		script = "@echo off\r\n" + script
	}
	path := filepath.Join(dir, name)
	require.NoError(t, os.WriteFile(path, []byte(script), 0755))
	t.Setenv("PATH", fmt.Sprintf("%s%c%s", dir, os.PathListSeparator, os.Getenv("PATH")))
}
