package reviewdiff

import (
	"fmt"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRenderForReview_IncludesSmallDiffsVerbatim(t *testing.T) {
	diff := DiffSet{
		PRNumber: 12,
		BaseSHA:  "base",
		HeadSHA:  "head",
		Source:   "github",
		Files: []ChangedFile{
			{
				Path:      "added.go",
				Status:    ChangeAdded,
				Additions: 2,
				Patch:     "@@ -0,0 +1,2 @@\n+package added\n+func Added() {}\n",
			},
			{
				Path:      "modified.go",
				Status:    ChangeModified,
				Additions: 1,
				Deletions: 1,
				Patch:     "@@ -1 +1 @@\n-old\n+new\n",
			},
			{
				Path:      "deleted.go",
				Status:    ChangeDeleted,
				Deletions: 2,
				Patch:     "@@ -1,2 +0,0 @@\n-package deleted\n-func Deleted() {}\n",
			},
			{
				Path:      "new_name.go",
				OldPath:   "old_name.go",
				Status:    ChangeRenamed,
				Additions: 1,
				Deletions: 1,
				Patch:     "@@ -1 +1 @@\n-oldName\n+newName\n",
			},
		},
	}

	result := RenderForReview(diff, RenderOptions{
		MaxTotalDiffBytes:        10000,
		MaxFileDiffBytes:         1000,
		MaxIncludedFiles:         10,
		MaxOmittedSummaryEntries: 10,
	})

	require.False(t, result.WasLimited)
	require.Len(t, result.IncludedFiles, 4)
	assert.Empty(t, result.OmittedFiles)
	assert.Empty(t, result.TruncatedFiles)
	assert.Contains(t, result.Text, "- Source: github")
	assert.Contains(t, result.Text, "- Base SHA: base")
	assert.Contains(t, result.Text, "- Head SHA: head")
	assert.Contains(t, result.Text, "- Total files: 4")
	assert.Contains(t, result.Text, "@@ -0,0 +1,2 @@\n+package added\n+func Added() {}\n")
	assert.Contains(t, result.Text, "@@ -1 +1 @@\n-old\n+new\n")
	assert.Contains(t, result.Text, "@@ -1,2 +0,0 @@\n-package deleted\n-func Deleted() {}\n")
	assert.Contains(t, result.Text, "- Old path: old_name.go")
	assert.Contains(t, result.Text, "@@ -1 +1 @@\n-oldName\n+newName\n")
	assert.NotContains(t, result.Text, "## Omitted files")
}

func TestGeneratedHeuristics(t *testing.T) {
	tests := []struct {
		name string
		path string
		want bool
	}{
		{name: "vendor prefix", path: "vendor/github.com/example/lib.go", want: true},
		{name: "nested vendor", path: "src/vendor/github.com/example/lib.go", want: true},
		{name: "dist prefix", path: "dist/app.js", want: true},
		{name: "build prefix", path: "build/app.js", want: true},
		{name: "coverage prefix", path: "coverage/index.html", want: true},
		{name: "node modules prefix", path: "node_modules/pkg/index.js", want: true},
		{name: "minified js", path: "assets/app.min.js", want: true},
		{name: "minified css", path: "assets/app.min.css", want: true},
		{name: "ordinary source", path: "internal/app/app.js", want: false},
		{name: "ordinary lockfile path", path: "package-lock.json", want: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, IsGeneratedPath(tt.path))
		})
	}
}

func TestHasGeneratedHeader(t *testing.T) {
	tests := []struct {
		name  string
		patch string
		want  bool
	}{
		{name: "code generated", patch: "// Code generated by tool. DO NOT EDIT.\n", want: true},
		{name: "do not edit", patch: "/* DO NOT EDIT */\n", want: true},
		{name: "generated by", patch: "# Generated by protoc\n", want: true},
		{name: "not generated", patch: "package main\n", want: false},
		{name: "header scan only", patch: strings.Repeat("x", 4097) + "DO NOT EDIT", want: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, HasGeneratedHeader(tt.patch))
		})
	}
}

func TestIsLargeLockfile_OnlyLargeLockfiles(t *testing.T) {
	tests := []struct {
		name      string
		path      string
		diffBytes int
		want      bool
	}{
		{name: "small package lock is not large", path: "package-lock.json", diffBytes: LargeLockfileDiffBytes - 1, want: false},
		{name: "large package lock", path: "package-lock.json", diffBytes: LargeLockfileDiffBytes, want: true},
		{name: "large yarn lock", path: "frontend/yarn.lock", diffBytes: LargeLockfileDiffBytes + 1, want: true},
		{name: "large go sum", path: "go.sum", diffBytes: LargeLockfileDiffBytes + 1, want: true},
		{name: "large ordinary file", path: "internal/app/app.go", diffBytes: LargeLockfileDiffBytes + 1, want: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, IsLargeLockfile(tt.path, tt.diffBytes))
		})
	}
}

func TestMarkGeneratedAndLarge(t *testing.T) {
	opts := RenderOptions{
		MaxTotalDiffBytes:        10000,
		MaxFileDiffBytes:         20,
		MaxIncludedFiles:         10,
		MaxOmittedSummaryEntries: 10,
	}

	tests := []struct {
		name          string
		file          ChangedFile
		wantGenerated bool
		wantLarge     bool
	}{
		{name: "generated path", file: ChangedFile{Path: "dist/app.js", Patch: "small"}, wantGenerated: true},
		{name: "generated header", file: ChangedFile{Path: "api.pb.go", Patch: "// Code generated by protoc. DO NOT EDIT.\n"}, wantGenerated: true, wantLarge: true},
		{name: "large lockfile", file: ChangedFile{Path: "yarn.lock", Patch: strings.Repeat("x", LargeLockfileDiffBytes)}, wantLarge: true},
		{name: "over per-file limit", file: ChangedFile{Path: "src/app.go", Patch: strings.Repeat("x", 21)}, wantLarge: true},
		{name: "small source", file: ChangedFile{Path: "src/app.go", Patch: "small"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := MarkGeneratedAndLarge(tt.file, opts)
			assert.Equal(t, tt.wantGenerated, got.Generated)
			assert.Equal(t, tt.wantLarge, got.Large)
		})
	}
}

func TestRenderForReview_SummarizesGeneratedBinaryLargeLockfileAndModeOnly(t *testing.T) {
	largeLockPatch := strings.Repeat("x", LargeLockfileDiffBytes)
	diff := DiffSet{
		Source:   "github",
		BaseSHA:  "base",
		HeadSHA:  "head",
		Warnings: []string{"source warning"},
		Files: []ChangedFile{
			{Path: "dist/app.js", Status: ChangeModified, Patch: "@@ -1 +1 @@\n-old\n+new\n"},
			{Path: "image.png", Status: ChangeAdded, Binary: true},
			{Path: "package-lock.json", Status: ChangeModified, Patch: largeLockPatch},
			{Path: "script.sh", Status: ChangeModified, PreviousMode: "100644", CurrentMode: "100755"},
		},
	}

	result := RenderForReview(diff, RenderOptions{
		MaxTotalDiffBytes:        LargeLockfileDiffBytes + 1000,
		MaxFileDiffBytes:         LargeLockfileDiffBytes + 100,
		MaxIncludedFiles:         10,
		MaxOmittedSummaryEntries: 10,
	})

	require.True(t, result.WasLimited)
	require.Len(t, result.OmittedFiles, 4)
	assert.Contains(t, result.Text, "- Warning: source warning")
	assert.Contains(t, result.Text, "dist/app.js (modified, +0/-0, reason: generated file)")
	assert.Contains(t, result.Text, "image.png (added, +0/-0, reason: binary file)")
	assert.Contains(t, result.Text, "package-lock.json (modified, +0/-0, reason: large lockfile diff)")
	assert.Contains(t, result.Text, "script.sh (modified, +0/-0, mode: 100644 -> 100755, reason: mode-only change)")
	assert.Contains(t, strings.Join(result.Warnings, "\n"), "omitted")
	assert.Contains(t, strings.Join(result.Warnings, "\n"), "generated")
	assert.Contains(t, strings.Join(result.Warnings, "\n"), "binary")
}

func TestRenderForReview_TruncatesPerFileDiff(t *testing.T) {
	result := RenderForReview(DiffSet{
		Source:  "github",
		BaseSHA: "base",
		HeadSHA: "head",
		Files: []ChangedFile{{
			Path:   "large.go",
			Status: ChangeModified,
			Patch:  "@@ -1 +1 @@\n" + strings.Repeat("+x\n", 20),
		}},
	}, RenderOptions{
		MaxTotalDiffBytes:        1000,
		MaxFileDiffBytes:         25,
		MaxIncludedFiles:         10,
		MaxOmittedSummaryEntries: 10,
	})

	require.True(t, result.WasLimited)
	require.Len(t, result.IncludedFiles, 1)
	require.Len(t, result.TruncatedFiles, 1)
	assert.Empty(t, result.OmittedFiles)
	assert.Contains(t, result.Text, "- Warning: truncated, reason: per-file diff byte limit reached")
	assert.Contains(t, result.Text, "[diff truncated]")
	assert.Contains(t, strings.Join(result.Warnings, "\n"), "truncated")
}

func TestRenderForReview_OmitsWhenTotalLimitWouldBeExceeded(t *testing.T) {
	result := RenderForReview(DiffSet{
		Source:  "github",
		BaseSHA: "base",
		HeadSHA: "head",
		Files: []ChangedFile{
			{Path: "one.go", Status: ChangeModified, Patch: strings.Repeat("a", 20)},
			{Path: "two.go", Status: ChangeModified, Patch: strings.Repeat("b", 20)},
		},
	}, RenderOptions{
		MaxTotalDiffBytes:        30,
		MaxFileDiffBytes:         100,
		MaxIncludedFiles:         10,
		MaxOmittedSummaryEntries: 10,
	})

	require.True(t, result.WasLimited)
	require.Len(t, result.IncludedFiles, 1)
	require.Len(t, result.OmittedFiles, 1)
	assert.Equal(t, "two.go", result.OmittedFiles[0].Path)
	assert.Equal(t, "total diff byte limit reached", result.OmittedFiles[0].OmitReason)
	assert.Contains(t, result.Text, "two.go (modified, +0/-0, reason: total diff byte limit reached)")
}

func TestRenderForReview_OmitsAfterMaxIncludedFiles(t *testing.T) {
	result := RenderForReview(DiffSet{
		Source:  "github",
		BaseSHA: "base",
		HeadSHA: "head",
		Files: []ChangedFile{
			{Path: "one.go", Status: ChangeModified, Patch: "one"},
			{Path: "two.go", Status: ChangeModified, Patch: "two"},
		},
	}, RenderOptions{
		MaxTotalDiffBytes:        100,
		MaxFileDiffBytes:         100,
		MaxIncludedFiles:         1,
		MaxOmittedSummaryEntries: 10,
	})

	require.True(t, result.WasLimited)
	require.Len(t, result.IncludedFiles, 1)
	require.Len(t, result.OmittedFiles, 1)
	assert.Equal(t, "max included file count reached", result.OmittedFiles[0].OmitReason)
	assert.Contains(t, result.Text, "two.go (modified, +0/-0, reason: max included file count reached)")
}

func TestRenderForReview_CapsOmittedSummaryEntries(t *testing.T) {
	files := make([]ChangedFile, 0, 4)
	for i := range 4 {
		files = append(files, ChangedFile{
			Path:   fmt.Sprintf("dist/%d.js", i),
			Status: ChangeModified,
			Patch:  "generated",
		})
	}

	result := RenderForReview(DiffSet{
		Source:  "github",
		BaseSHA: "base",
		HeadSHA: "head",
		Files:   files,
	}, RenderOptions{
		MaxTotalDiffBytes:        100,
		MaxFileDiffBytes:         100,
		MaxIncludedFiles:         10,
		MaxOmittedSummaryEntries: 2,
	})

	require.Len(t, result.OmittedFiles, 4)
	assert.Contains(t, result.Text, "dist/0.js")
	assert.Contains(t, result.Text, "dist/1.js")
	assert.NotContains(t, result.Text, "dist/2.js (")
	assert.NotContains(t, result.Text, "dist/3.js (")
	assert.Contains(t, result.Text, "- ... 2 additional omitted files not shown")
}

func TestRenderForReview_SmallLockfileDiffIsIncluded(t *testing.T) {
	patch := "@@ -1 +1 @@\n-old\n+new\n"
	result := RenderForReview(DiffSet{
		Source:  "github",
		BaseSHA: "base",
		HeadSHA: "head",
		Files: []ChangedFile{{
			Path:   "package-lock.json",
			Status: ChangeModified,
			Patch:  patch,
		}},
	}, RenderOptions{
		MaxTotalDiffBytes:        1000,
		MaxFileDiffBytes:         1000,
		MaxIncludedFiles:         10,
		MaxOmittedSummaryEntries: 10,
	})

	require.False(t, result.WasLimited)
	require.Len(t, result.IncludedFiles, 1)
	assert.Empty(t, result.OmittedFiles)
	assert.Contains(t, result.Text, patch)
}

func TestDefaultRenderOptions(t *testing.T) {
	opts := DefaultRenderOptions()
	assert.Positive(t, opts.MaxTotalDiffBytes)
	assert.Positive(t, opts.MaxFileDiffBytes)
	assert.Positive(t, opts.MaxIncludedFiles)
	assert.Positive(t, opts.MaxOmittedSummaryEntries)

	normalized := normalizeOptions(RenderOptions{})
	assert.Equal(t, opts, normalized)
}
