version: "2"
linters:
  enable:
    - gocritic
    - gosec
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
    gocritic:
      disabled-checks:
        - ifElseChain
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF1012
        - -ST1000
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test.go
      - linters:
          - gosec
        text: G204
      - linters:
          - gosec
        text: G301
      - linters:
          - gosec
        text: G304
      - linters:
          - gosec
        text: G104
      - linters:
          - gosec
        text: G302
      - linters:
          - gosec
        text: G306
      - linters:
          - gosec
        text: G702
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
